### ISSUE TITLE
每次complete事件的时候都是触发两次

### ISSUE THREAD

**Issue by woaixiangbao** [hotoo/apassword#5]
我发现，按照你的doc里面的方法写：
new APassword("input.apassword")
  .on("complete", function(value){

```
alert(value);
```

}).render();

会alert两遍value值。也就是执行了两次complete。我修改了spassword里面的那个"__event.on"为__event.once才能正常的alert一次。不知道这个算不算bug。还是我哪里写错了。

**Comment by hotoo** [comment]
为了兼容老的 Android/iOS 系统，同时使用了 `input` 和 `keyup` 事件，对于同时支持这两种事件的浏览器就会触发两次 complete 事件。
